// Code generated by mockery v2.44.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AIClient is an autogenerated mock type for the AIClient type
type AIClient struct {
	mock.Mock
}

type AIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *AIClient) EXPECT() *AIClient_Expecter {
	return &AIClient_Expecter{mock: &_m.Mock}
}

// AskQuestion provides a mock function with given fields: ctx, question
func (_m *AIClient) AskQuestion(ctx context.Context, question string) (string, error) {
	ret := _m.Called(ctx, question)

	if len(ret) == 0 {
		panic("no return value specified for AskQuestion")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, question)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, question)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, question)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AIClient_AskQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AskQuestion'
type AIClient_AskQuestion_Call struct {
	*mock.Call
}

// AskQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - question string
func (_e *AIClient_Expecter) AskQuestion(ctx interface{}, question interface{}) *AIClient_AskQuestion_Call {
	return &AIClient_AskQuestion_Call{Call: _e.mock.On("AskQuestion", ctx, question)}
}

func (_c *AIClient_AskQuestion_Call) Run(run func(ctx context.Context, question string)) *AIClient_AskQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AIClient_AskQuestion_Call) Return(_a0 string, _a1 error) *AIClient_AskQuestion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AIClient_AskQuestion_Call) RunAndReturn(run func(context.Context, string) (string, error)) *AIClient_AskQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// NewAIClient creates a new instance of AIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AIClient {
	mock := &AIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
